name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run buildscript
        run: npm run build

      - name: Upload entire build folder to Vercel Blob
        uses: 634750802/vercel-blob-action@master
        with:
          source: ".vitepress/dist/"
          destination: "conversational-ai-for-the-curious/builds/"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          add-random-suffix: false
